//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMixIssue.NetFramework47.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Author
    {
        public long Oid { get; set; }
        public string PenName { get; set; }
        public long ApplicationUserId { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
